name: Bug report
description: Report a bug or regression
title: "bug: "
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Preflight
      options:
        - label: I searched existing issues
          required: true
        - label: I ran with --dry-run and captured output
          required: true
        - label: I read the troubleshooting docs
          required: false
  - type: dropdown
    attributes:
      label: Installation mode
      options:
        - Project mode (--project-dir ...)
        - Global mode (--target-home ...)
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened
      description: A clear and concise description of the bug.
      placeholder: When I run ./install.sh --project-dir ..., it ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Provide minimal, repeatable steps.
      placeholder: |-
        1. Unzip the bundle
        2. Run ./install.sh --project-dir /path/to/project --dry-run
        3. See error ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: The installer should ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      placeholder: The installer fails with ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Command and output
      description: Paste the exact command and full output (redact secrets).
      render: text
    validations:
      required: true
  - type: input
    attributes:
      label: OS
      placeholder: macOS 14.3, Ubuntu 22.04, Windows 11
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
      placeholder: python3 --version
    validations:
      required: true
  - type: input
    attributes:
      label: Node.js version
      placeholder: node --version
    validations:
      required: true
  - type: input
    attributes:
      label: Git version
      placeholder: git --version
    validations:
      required: true
  - type: input
    attributes:
      label: Bundle version
      description: Git commit SHA or release tag.
      placeholder: git rev-parse HEAD
    validations:
      required: false
